spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:taskdb}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:taskuser}
    password: ${DB_PASSWORD:taskpassword}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080
